language: node_js
node_js:
    - "12"
script:
    - npm run build
    - npm run lint
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/CV-ng
    on:
        branch: master
