language: node_js
node_js:
    - "12"
lint:
    - npm run lint
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/CV-ng
    on:
        branch: master
